analyzer:
  errors:
    sort_pub_dependencies: ignore
    implementation_imports: error
    missing_required_param: error
    must_be_immutable: error
    missing_return: warning
    non_constant_identifier_names: ignore
    require_trailing_commas: ignore
    todo: warning

linter:
  rules:
    - file_names
    - package_names
    - unnecessary_parenthesis
    - sort_constructors_first
    - curly_braces_in_flow_control_structures
    - prefer_if_elements_to_conditional_expressions
    - prefer_contains
    - prefer_single_quotes
    - prefer_final_in_for_each
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_spread_collections
    - await_only_futures
    - avoid_returning_null_for_future
    - avoid_returning_null_for_void
    - avoid_init_to_null
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - avoid_redundant_argument_values
    - avoid_function_literals_in_foreach_calls
    - avoid_escaping_inner_quotes
    - use_string_buffers
    - unawaited_futures
